FROM nfcore/base

LABEL authors="phil@lifebit.ai" \
      description="Docker image containing fastqc & multiqc for JAX workshop"

RUN conda config --add channels defaults
RUN conda config --add channels conda-forge

    