#!/bin/bash
#PBS -l nodes=1:ppn=2
#PBS -l walltime=0:30:00
#PBS -l mem=4GB
#PBS -q batch
#PBS -N blob3
#PBS -t 0-377
#PBS -o pbslogs/$PBS_JOBNAME.o
#PBS -e pbslogs/$PBS_JOBNAME.e

cd $PBS_O_WORKDIR
FILE="/projects/chuang-lab/jnh/flower/data/movies/41586_2019_1429_MOESM3_ESM.mov"
. /projects/chuang-lab/jnh/miniconda3/etc/profile.d/conda.sh
conda activate flower
flowermodel blob --filename $FILE --blob-index $PBS_ARRAYID
